apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: yopass
  namespace: yopass
spec:
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yopass